### ISSUE TITLE
Unable to build without CUDA

### ISSUE THREAD

**Issue by damnkrat** [evilsocket/cake#16]
Tried on debian server and termux. Results are same

```bash
CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true RUST_BACKTRACE=full cargo build --release
warning: /home/dankcat/cake/cake-ios/Cargo.toml: `crate_type` is deprecated in favor of `crate-type` and will not work in the 2024 edition
(in the `cake` library target)
   Compiling cudarc v0.11.7
   Compiling candle-kernels v0.6.0
   Compiling zstd-sys v2.0.12+zstd.1.5.6
   Compiling block-buffer v0.10.4
error: failed to run custom build command for `candle-kernels v0.6.0`

Caused by:
  process didn't exit successfully: `/home/dankcat/cake/target/release/build/candle-kernels-15ec0a2c0042f062/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=src/compatibility.cuh
  cargo:rerun-if-changed=src/cuda_utils.cuh
  cargo:rerun-if-changed=src/binary_op_macros.cuh
  cargo:info=["/usr", "/usr/local/cuda", "/opt/cuda", "/usr/lib/cuda", "C:/Program Files/NVIDIA GPU Computing Toolkit", "C:/CUDA"]
  cargo:rerun-if-env-changed=CUDA_COMPUTE_CAP

  --- stderr
  thread 'main' panicked at /home/dankcat/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen_cuda-0.1.5/src/lib.rs:489:18:
  `nvidia-smi` failed. Ensure that you have CUDA installed and that `nvidia-smi` is in your PATH.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  stack backtrace:
     0:     0x55c93d687785 - std::backtrace_rs::backtrace::libunwind::trace::h1a07e5dba0da0cd2
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
     1:     0x55c93d687785 - std::backtrace_rs::backtrace::trace_unsynchronized::h61b9b8394328c0bc
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55c93d687785 - std::sys_common::backtrace::_print_fmt::h1c5e18b460934cff
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:68:5
     3:     0x55c93d687785 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e1a1972118942ad
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x55c93d6ac13b - core::fmt::rt::Argument::fmt::h07af2b4071d536cd
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/rt.rs:165:63
     5:     0x55c93d6ac13b - core::fmt::write::hc090a2ffd6b28c4a
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/mod.rs:1157:21
     6:     0x55c93d68420f - std::io::Write::write_fmt::h8898bac6ff039a23
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/io/mod.rs:1832:15
     7:     0x55c93d68755e - std::sys_common::backtrace::_print::h4e80c5803d4ee35b
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:47:5
     8:     0x55c93d68755e - std::sys_common::backtrace::print::ha96650907276675e
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:34:9
     9:     0x55c93d688a49 - std::panicking::default_hook::{{closure}}::h215c2a0a8346e0e0
    10:     0x55c93d68878d - std::panicking::default_hook::h207342be97478370
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:298:9
    11:     0x55c93d688ee3 - std::panicking::rust_panic_with_hook::hac8bdceee1e4fe2c
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:795:13
    12:     0x55c93d688dc4 - std::panicking::begin_panic_handler::{{closure}}::h00d785e82757ce3c
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:664:13
    13:     0x55c93d687c49 - std::sys_common::backtrace::__rust_end_short_backtrace::h1628d957bcd06996
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
    14:     0x55c93d688af7 - rust_begin_unwind
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
    15:     0x55c93d5e10f3 - core::panicking::panic_fmt::hdc63834ffaaefae5
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
    16:     0x55c93d5e1546 - core::result::unwrap_failed::h82b551e0ff2b2176
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
    17:     0x55c93d5f00d8 - core::result::Result<T,E>::expect::h0d780f1427a920a0
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1034:23
    18:     0x55c93d6058fc - bindgen_cuda::compute_cap::h544f29d1dbea88ae
                                 at /home/dankcat/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen_cuda-0.1.5/src/lib.rs:485:19
    19:     0x55c93d60216f - <bindgen_cuda::Builder as core::default::Default>::default::hc8d3c33e79e06ed7
                                 at /home/dankcat/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen_cuda-0.1.5/src/lib.rs:48:27
    20:     0x55c93d5e2e5f - build_script_build::main::h601c987ee98bf43b
                                 at /home/dankcat/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-kernels-0.6.0/build.rs:7:19
    21:     0x55c93d5e270b - core::ops::function::FnOnce::call_once::h3413b6fc62df34af
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
    22:     0x55c93d5e1e6e - std::sys_common::backtrace::__rust_begin_short_backtrace::hbdfe41c52daab1ec
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155:18
    23:     0x55c93d5e22d1 - std::rt::lang_start::{{closure}}::h51c795f7d1b1d218
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:159:18
    24:     0x55c93d67ead0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6abeee5a7794ceb5
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:284:13
    25:     0x55c93d67ead0 - std::panicking::try::do_call::hd6e966bb06877057
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
    26:     0x55c93d67ead0 - std::panicking::try::hc9b3807f5768cb19
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
    27:     0x55c93d67ead0 - std::panic::catch_unwind::h94a757c154076c6e
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
    28:     0x55c93d67ead0 - std::rt::lang_start_internal::{{closure}}::hc5223fb36050c743
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:48
    29:     0x55c93d67ead0 - std::panicking::try::do_call::hddf7b4e1ebeb3f69
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
    30:     0x55c93d67ead0 - std::panicking::try::h1842860a1f941a31
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
    31:     0x55c93d67ead0 - std::panic::catch_unwind::h009016ccf811d4c3
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
    32:     0x55c93d67ead0 - std::rt::lang_start_internal::h3ed4fe7b2f419135
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:20
    33:     0x55c93d5e22aa - std::rt::lang_start::hff6e3b582a875b8d
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:158:17
    34:     0x55c93d5e306e - main
    35:     0x7f40ce51524a - <unknown>
    36:     0x7f40ce515305 - __libc_start_main
    37:     0x55c93d5e1761 - _start
    38:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `cudarc v0.11.7`

Caused by:
  process didn't exit successfully: `/home/dankcat/cake/target/release/build/cudarc-5c6a5152ed8f4c4d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CUDA_ROOT
  cargo:rerun-if-env-changed=CUDA_PATH
  cargo:rerun-if-env-changed=CUDA_TOOLKIT_ROOT_DIR

  --- stderr
  thread 'main' panicked at /home/dankcat/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cudarc-0.11.7/build.rs:55:10:
  Failed to execute `nvcc`: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  stack backtrace:
     0:     0x564532b54cf5 - std::backtrace_rs::backtrace::libunwind::trace::h1a07e5dba0da0cd2
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
     1:     0x564532b54cf5 - std::backtrace_rs::backtrace::trace_unsynchronized::h61b9b8394328c0bc
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x564532b54cf5 - std::sys_common::backtrace::_print_fmt::h1c5e18b460934cff
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:68:5
     3:     0x564532b54cf5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e1a1972118942ad
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x564532b75a2b - core::fmt::rt::Argument::fmt::h07af2b4071d536cd
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/rt.rs:165:63
     5:     0x564532b75a2b - core::fmt::write::hc090a2ffd6b28c4a
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/mod.rs:1157:21
     6:     0x564532b5290f - std::io::Write::write_fmt::h8898bac6ff039a23
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/io/mod.rs:1832:15
     7:     0x564532b54ace - std::sys_common::backtrace::_print::h4e80c5803d4ee35b
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:47:5
     8:     0x564532b54ace - std::sys_common::backtrace::print::ha96650907276675e
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:34:9
     9:     0x564532b55d89 - std::panicking::default_hook::{{closure}}::h215c2a0a8346e0e0
    10:     0x564532b55acd - std::panicking::default_hook::h207342be97478370
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:298:9
    11:     0x564532b56223 - std::panicking::rust_panic_with_hook::hac8bdceee1e4fe2c
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:795:13
    12:     0x564532b56104 - std::panicking::begin_panic_handler::{{closure}}::h00d785e82757ce3c
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:664:13
    13:     0x564532b551b9 - std::sys_common::backtrace::__rust_end_short_backtrace::h1628d957bcd06996
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
    14:     0x564532b55e37 - rust_begin_unwind
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
    15:     0x564532b25f53 - core::panicking::panic_fmt::hdc63834ffaaefae5
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
    16:     0x564532b26366 - core::result::unwrap_failed::h82b551e0ff2b2176
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
    17:     0x564532b2c438 - core::result::Result<T,E>::expect::h33784a2d338b94a7
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1034:23
    18:     0x564532b316f6 - build_script_build::cuda_version_from_build_system::h4a38442c7c737c00
                                 at /home/dankcat/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cudarc-0.11.7/build.rs:52:18
    19:     0x564532b3133a - build_script_build::main::h77dc56d88b14ee07
                                 at /home/dankcat/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cudarc-0.11.7/build.rs:37:34
    20:     0x564532b2e5cb - core::ops::function::FnOnce::call_once::h2274ad654a6bbd1b
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
    21:     0x564532b340fe - std::sys_common::backtrace::__rust_begin_short_backtrace::hff1eff237bf98703
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155:18
    22:     0x564532b2b3d1 - std::rt::lang_start::{{closure}}::h214b04bede10fd10
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:159:18
    23:     0x564532b4f850 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6abeee5a7794ceb5
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:284:13
    24:     0x564532b4f850 - std::panicking::try::do_call::hd6e966bb06877057
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
    25:     0x564532b4f850 - std::panicking::try::hc9b3807f5768cb19
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
    26:     0x564532b4f850 - std::panic::catch_unwind::h94a757c154076c6e
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
    27:     0x564532b4f850 - std::rt::lang_start_internal::{{closure}}::hc5223fb36050c743
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:48
    28:     0x564532b4f850 - std::panicking::try::do_call::hddf7b4e1ebeb3f69
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
    29:     0x564532b4f850 - std::panicking::try::h1842860a1f941a31
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
    30:     0x564532b4f850 - std::panic::catch_unwind::h009016ccf811d4c3
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
    31:     0x564532b4f850 - std::rt::lang_start_internal::h3ed4fe7b2f419135
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:20
    32:     0x564532b2b3aa - std::rt::lang_start::ha16ce9452477e973
                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:158:17
    33:     0x564532b331fe - main
    34:     0x7fec3bef624a - <unknown>
    35:     0x7fec3bef6305 - __libc_start_main
    36:     0x564532b26541 - _start
    37:                0x0 - <unknown>
```

**Comment by evilsocket** [comment]
>  Failed to execute `nvcc`: Os { code: 2, kind: NotFound, message: "No such file or directory" }

NVCC not found in $PATH, so either CUDA is not installed, or its bin folder is not in $PATH.

**Comment by evilsocket** [comment]
yes i need to add acceleration as selectable features

**Comment by evilsocket** [comment]
@damnkrat fixed! if you pull the changes, cargo build --release will build without acceleration (check the README for CUDA and Metal).
